tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 1200    # Timeout in seconds.    
        runs: 3
filter:
    excluded_paths: [bin/*, tests/*]

checks:
    php:
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        sql_injection_vulnerabilities: true
        side_effects_or_types: true
        useless_calls: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_php_tag_first: true
        avoid_corrupting_byteorder_marks: true
        avoid_tab_indentation: true
        avoid_unnecessary_concatenation: true
        avoid_useless_overridden_methods: true
        code_rating: true
        deadlock_detection_in_loops: true
        duplication: true
        fix_doc_comments: true
        fix_identation_4spaces: true
        fix_line_ending: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        newline_at_end_of_file: true
        no_debug_code: true
        no_unnecessary_function_call_in_for_loop: true
        prefer_unix_line_ending: true
