tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

checks:
    php:
        variable_existence: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        sql_injection_vulnerabilities: true
        duplication: true
        no_long_variable_names:
            maximum: '20'
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        more_specific_types_in_doc_comments: true
        fix_doc_comments: true
        remove_php_closing_tag: true
        remove_extra_empty_lines: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_identation_4spaces: true
        fix_line_ending: true
        fix_linefeed: true
        fix_php_opening_tag: true
