language: php
php:
 - "5.4"
 - "5.5"
 - "7"
 - "hhvm"

env:
 - ATIAA_DRIVER=sqlite ATIAA_FILE=sqlite.db ATIAA_PDO_DSN='sqlite:sqlite.db' ATIAA_SKIP_DB=yes
 - ATIAA_DRIVER=mysql ATIAA_HOST=localhost ATIAA_USER=root ATIAA_DBNAME=atiaa_test ATIAA_PDO_DSN='mysql:host=localhost;dbname=atiaa_test;user=root'
 - ATIAA_DRIVER=postgresql ATIAA_HOST=localhost ATIAA_USER=postgres ATIAA_DBNAME=atiaa_test ATIAA_HAS_SCHEMAS=yes ATIAA_PDO_DSN='pgsql:host=localhost;dbname=atiaa_test;user=postgres'


matrix:
 allow_failures:
  - php: "7"
 include:
  - php: "5.6"
    env: ATIAA_DRIVER=mysql ATIAA_HOST=localhost ATIAA_USER=root ATIAA_DBNAME=atiaa_test ATIAA_PDO_DSN='mysql:host=localhost;dbname=atiaa_test;user=root' COVERAGE=yes
  - php: "5.6"
    env: ATIAA_DRIVER=postgresql ATIAA_HOST=localhost ATIAA_USER=postgres ATIAA_DBNAME=atiaa_test ATIAA_HAS_SCHEMAS=yes ATIAA_PDO_DSN='pgsql:host=localhost;dbname=atiaa_test;user=postgres' COVERAGE=yes
  - php: "5.6"
    env: ATIAA_DRIVER=sqlite ATIAA_FILE=sqlite.db ATIAA_PDO_DSN='sqlite:sqlite.db' ATIAA_SKIP_DB=yes COVERAGE=yes
 exclude:
  - php: "hhvm"
    env: ATIAA_DRIVER=postgresql ATIAA_HOST=localhost ATIAA_USER=postgres ATIAA_DBNAME=atiaa_test ATIAA_HAS_SCHEMAS=yes ATIAA_PDO_DSN='pgsql:host=localhost;dbname=atiaa_test;user=postgres'
  
before_script:
 - composer install --prefer-dist
 - if [ "$ATIAA_DRIVER" = "postgresql" ]; then psql -c 'create database atiaa_test;' -U postgres; fi
 - if [ "$ATIAA_DRIVER" = "postgresql" ]; then psql -f tests/databases/postgresql.sql -U postgres -d atiaa_test; fi
 - if [ "$ATIAA_DRIVER" = "mysql" ]; then mysql -e 'create database atiaa_test;'; fi
 - if [ "$ATIAA_DRIVER" = "mysql" ]; then mysql atiaa_test < tests/databases/mysql.sql; fi
 - if [ "$ATIAA_DRIVER" = "sqlite" ]; then sqlite3 sqlite.db < tests/databases/sqlite.sql; fi

services:
 - mysql
 - postgresql

script: vendor/bin/phpunit --coverage-clover coverage.clover --configuration tests/config/travis.xml
after_script: if [ "$COVERAGE" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
