name: Test
on: [push]
jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db:
          - env:
              ATIAA_DRIVER: sqlite
              ATIAA_FILE: sqlite.db
              ATIAA_PDO_DSN: sqlite:sqlite.db
              ATIAA_SKIP_DB: yes
            dsn: sqlite:sqlite.db

#              ATIAA_DRIVER: sqlite
#              ATIAA_FILE: sqlite.db
#              ATIAA_PDO_DSN: sqlite:sqlite.db
#              ATIAA_SKIP_DB: yes

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
      - name: Running composer
        run: composer install
      - name: Running php unit tests
        env: ${{ matrix.db.env }}
        run: vendor/bin/phpunit  --coverage-clover coverage.clover -c tests/config/github.xml
      - name: Downloading Ocular Tool
        run: composer global require scrutinizer/ocular dev-master
      - name: Uploading Code Metrics
        run: php ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover