name: Test
on: [push]
jobs:
  Integration:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - '3306:3306'
    strategy:
      matrix:
        db:
          - env:
              ATIAA_DRIVER: sqlite
              ATIAA_FILE: sqlite.db
              ATIAA_PDO_DSN: sqlite:sqlite.db
              ATIAA_SKIP_DB: yes
            initialize: sqlite3 sqlite.db < tests/databases/sqlite.sql

          - env:
              ATIAA_DRIVER: mysql
              ATIAA_HOST: localhost
              ATIAA_USER: root
              ATIAA_DBNAME: atiaa_test
              ATIAA_PDO_DSN: mysql:host=localhost;dbname=atiaa_test;user=root
            initialize: |
                mysql -h mysql -e 'create database atiaa_test;'
                mysql -h mysql atiaa_test < tests/databases/mysql.sql
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
      - name: Running composer
        run: composer install
      - name: Initializing the database
        run: ${{ matrix.db.initialize }}
      - name: Running php unit tests
        env: ${{ matrix.db.env }}
        run: vendor/bin/phpunit  --coverage-clover coverage.clover -c tests/config/github.xml
      - name: Downloading Ocular Tool
        run: composer global require scrutinizer/ocular dev-master
      - name: Uploading Code Metrics
        run: php ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover